### ISSUE TITLE
Panic in pipeline.MarshalRESP

### ISSUE THREAD

**Issue by fastest963** [mediocregopher/radix#144]
We're running commit:
```
github.com/mediocregopher/radix (git) - a2b04d3 Merge pull request #139 from nussjustin/fix-implicit-pipelining-net-error-handling
```
When we started our application it immediately panic'd with:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xb213ce]
goroutine 275 [running]:
github.com/mediocregopher/radix.(*pipelinerCmd).MarshalRESP(0xc000473c40, 0x12d3280, 0xc0001c95b0, 0xc000016cf8, 0x4138a5)
<autogenerated>:1 +0x2e
github.com/mediocregopher/radix.pipeline.MarshalRESP(0xc0001c9790, 0x1, 0x1, 0x12d3280, 0xc0001c95b0, 0x18, 0xc0005869a0)
/opt/TeamCityBuild/work/rachel-2/524c221af2f6e433/.deps/src/github.com/mediocregopher/radix/action.go:466 +0x72
github.com/mediocregopher/radix.(*connWrap).Encode(0xc000586640, 0x12d66c0, 0xc0005869a0, 0xc0005869a0, 0xc000016e20)
/opt/TeamCityBuild/work/rachel-2/524c221af2f6e433/.deps/src/github.com/mediocregopher/radix/radix.go:239 +0x4f
github.com/mediocregopher/radix.(*ioErrConn).Encode(0xc000586660, 0x12d66c0, 0xc0005869a0, 0xc0005869a0, 0x1b93428)
/opt/TeamCityBuild/work/rachel-2/524c221af2f6e433/.deps/src/github.com/mediocregopher/radix/pool.go:40 +0x5c
github.com/mediocregopher/radix.pipelinerPipeline.Run(0xc0001c9790, 0x1, 0x1, 0x12f5d20, 0xc000586660, 0x23fe5b85, 0x291817668a2057)
/opt/TeamCityBuild/work/rachel-2/524c221af2f6e433/.deps/src/github.com/mediocregopher/radix/pipeliner.go:225 +0xa8
github.com/mediocregopher/radix.(*ioErrConn).Do(...)
/opt/TeamCityBuild/work/rachel-2/524c221af2f6e433/.deps/src/github.com/mediocregopher/radix/pool.go:61
github.com/mediocregopher/radix.(*Pool).Do(0xc000164d00, 0x12e1360, 0xc000586980, 0xc000586980, 0x1)
/opt/TeamCityBuild/work/rachel-2/524c221af2f6e433/.deps/src/github.com/mediocregopher/radix/pool.go:607 +0xf0
github.com/mediocregopher/radix.(*pipeliner).flush.func1(0xc000442d80, 0xc0001c9790, 0x1, 0x1)
/opt/TeamCityBuild/work/rachel-2/524c221af2f6e433/.deps/src/github.com/mediocregopher/radix/pipeliner.go:182 +0x108
created by github.com/mediocregopher/radix.(*pipeliner).flush
/opt/TeamCityBuild/work/rachel-2/524c221af2f6e433/.deps/src/github.com/mediocregopher/radix/pipeliner.go:173 +0x8f
```

Since this happened during initialization I have to imagine its caused by something with:
```
df := func(network, addr string) (radix.Client, error) {
	...
	return radix.NewPool(network, addr, poolSize,
			radix.PoolConnFunc(func(network, addr string) (radix.Conn, error) {
				return radix.Dial(network, addr,
					radix.DialTimeout(timeout),
				)
			}),
			radix.PoolOnEmptyCreateAfter(100*time.Millisecond),
			radix.PoolOnFullBuffer(poolSize*10, time.Second),
		)
	}
}
...
conn, err := df("tcp", addr)
if err != nil {
  return nil, err
}
defer conn.Close()

var c radix.Client
err = conn.Do(radix.Cmd(nil, "CLUSTER", "SLOTS"))
if err == nil {
  c, err = radix.NewCluster([]string{ar.Addr},
    radix.ClusterPoolFunc(df),
  )
} else if isClusterNotSupportedError(err) {
  c, err = df("tcp", ar.Addr)
}
```

I have to imagine its something with `defer conn.Close()` and that somehow something is still trying to use that after its closed but I'm not actually sure that it ever got past `err = conn.Do(radix.Cmd(nil, "CLUSTER", "SLOTS"))` so that could also be the issue.

**Comment by fastest963** [comment]
Separately in a different application we managed to run across:
```
==================
WARNING: DATA RACE
Read at 0x00c0002d88e0 by goroutine 59:
  github.com/mediocregopher/radix.(*pipelinerCmd).MarshalRESP()
      <autogenerated>:1 +0x50
  github.com/mediocregopher/radix.pipeline.MarshalRESP()
      /opt/TeamCityBuild/work/rachel-3/3c197426a0d40b59/.deps/src/github.com/mediocregopher/radix/action.go:466 +0x8f
  github.com/mediocregopher/radix.(*pipelinerPipeline).MarshalRESP()
      <autogenerated>:1 +0x87
  github.com/mediocregopher/radix.(*connWrap).Encode()
      /opt/TeamCityBuild/work/rachel-3/3c197426a0d40b59/.deps/src/github.com/mediocregopher/radix/radix.go:239 +0x7f
  github.com/mediocregopher/radix.(*ioErrConn).Encode()
      /opt/TeamCityBuild/work/rachel-3/3c197426a0d40b59/.deps/src/github.com/mediocregopher/radix/pool.go:40 +0x8a
  github.com/mediocregopher/radix.pipelinerPipeline.Run()
      /opt/TeamCityBuild/work/rachel-3/3c197426a0d40b59/.deps/src/github.com/mediocregopher/radix/pipeliner.go:225 +0xbb
  github.com/mediocregopher/radix.(*pipelinerPipeline).Run()
      <autogenerated>:1 +0x8a
  github.com/mediocregopher/radix.(*Pool).Do()
      /opt/TeamCityBuild/work/rachel-3/3c197426a0d40b59/.deps/src/github.com/mediocregopher/radix/pool.go:61 +0x12d
  github.com/mediocregopher/radix.(*pipeliner).flush.func1()
      /opt/TeamCityBuild/work/rachel-3/3c197426a0d40b59/.deps/src/github.com/mediocregopher/radix/pipeliner.go:182 +0x128

Previous write at 0x00c0002d88e0 by goroutine 27:
  github.com/mediocregopher/radix.(*pipeliner).Do()
      /opt/TeamCityBuild/work/rachel-3/3c197426a0d40b59/.deps/src/github.com/mediocregopher/radix/pipeliner.go:216 +0x161
  github.com/mediocregopher/radix.(*Pool).Do()
      /opt/TeamCityBuild/work/rachel-3/3c197426a0d40b59/.deps/src/github.com/mediocregopher/radix/pool.go:596 +0x222
  github.com/mediocregopher/radix.NewPool.func2()
      /opt/TeamCityBuild/work/rachel-3/3c197426a0d40b59/.deps/src/github.com/mediocregopher/radix/pool.go:353 +0xb6
  github.com/mediocregopher/radix.(*Pool).atIntervalDo.func1()
      /opt/TeamCityBuild/work/rachel-3/3c197426a0d40b59/.deps/src/github.com/mediocregopher/radix/pool.go:448 +0xc4

Goroutine 59 (running) created at:
  github.com/mediocregopher/radix.(*pipeliner).flush()
      /opt/TeamCityBuild/work/rachel-3/3c197426a0d40b59/.deps/src/github.com/mediocregopher/radix/pipeliner.go:173 +0xb5
  github.com/mediocregopher/radix.(*pipeliner).reqLoop()
      /opt/TeamCityBuild/work/rachel-3/3c197426a0d40b59/.deps/src/github.com/mediocregopher/radix/pipeliner.go:163 +0x5e9
  github.com/mediocregopher/radix.newPipeliner.func1()
      /opt/TeamCityBuild/work/rachel-3/3c197426a0d40b59/.deps/src/github.com/mediocregopher/radix/pipeliner.go:64 +0x68

Goroutine 27 (running) created at:
  github.com/mediocregopher/radix.(*Pool).atIntervalDo()
      /opt/TeamCityBuild/work/rachel-3/3c197426a0d40b59/.deps/src/github.com/mediocregopher/radix/pool.go:441 +0x84
  github.com/mediocregopher/radix.NewPool()
      /opt/TeamCityBuild/work/rachel-3/3c197426a0d40b59/.deps/src/github.com/mediocregopher/radix/pool.go:353 +0x93f
  bitbucket.org/levenlabs/llib/ldb.NewRedis.func1()
      /opt/TeamCityBuild/work/rachel-3/3c197426a0d40b59/.deps/src/bitbucket.org/levenlabs/llib/ldb/redis.go:42 +0x66c
  bitbucket.org/levenlabs/llib/ldb.NewRedis()
      /opt/TeamCityBuild/work/rachel-3/3c197426a0d40b59/.deps/src/bitbucket.org/levenlabs/llib/ldb/redis.go:61 +0x1a2
  bitbucket.org/levenlabs/llib/ldb.ConfiguredRedis.func1()
      /opt/TeamCityBuild/work/rachel-3/3c197426a0d40b59/.deps/src/bitbucket.org/levenlabs/llib/ldb/redis.go:114 +0x35b
  bitbucket.org/levenlabs/llib/lflag.Parse()
      /opt/TeamCityBuild/work/rachel-3/3c197426a0d40b59/.deps/src/bitbucket.org/levenlabs/llib/lflag/lflag.go:423 +0x6e3
  bitbucket.org/levenlabs/llib/lflag.Configure()
      /opt/TeamCityBuild/work/rachel-3/3c197426a0d40b59/.deps/src/bitbucket.org/levenlabs/llib/lflag/lflag.go:440 +0x14c
  _/opt/TeamCityBuild/work/rachel-3/3c197426a0d40b59/lcache.init.0()
      /opt/TeamCityBuild/work/rachel-3/3c197426a0d40b59/lcache/lcache_test.go:7 +0x3c
  _/opt/TeamCityBuild/work/rachel-3/3c197426a0d40b59/lcache.init()
      <autogenerated>:1 +0x100
  main.init()
      <autogenerated>:1 +0xa1
==================
```

**Comment by nussjustin** [comment]
Looks like we're reusing a `*pipelinerCmd` somehow. I still don't see how this could happen but I will take another look.

**Comment by nussjustin** [comment]
Ok, I think I know how this can happen. We can end up sending two values to the `resCh` of a `*pipelinerCmd` and since `*pipelinerCmd`s get reused, we can accidentally send a value on an reused instance.

**Comment by fastest963** [comment]
I think what's happening is that it's writing to ```
req.(*pipelinerCmd).resCh <- errConn.Decode(req)
``` 
but then if `Do` fails in `flush` then it's also doing:
```
select {
case req.(*pipelinerCmd).resCh <- err:
default:
}
```

So `resCh` could be written to twice which could cause the second use of it to immediately call `poolPipelinerCmd` which would clear out the CmdAction.

**Comment by fastest963** [comment]
Looks like we both came to the same conclusion. Since this was recently changed (https://github.com/mediocregopher/radix/pull/139) it seems like a good candidate.

**Comment by fastest963** [comment]
Oh, it seems like my panic is the same as the one in #126.

**Comment by nussjustin** [comment]
Will send a fix in a few minutes / seconds.
