### ISSUE TITLE
panic in goroutine use pipeline+FlatCmd

### ISSUE THREAD

**Issue by xuecai** [mediocregopher/radix#148]
i update code to master , it still panic.

```shell
fatal error: concurrent map writes

goroutine 23280 [running]:
runtime.throw(0xf5deb9, 0x15)
        /usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc013ead668 sp=0xc013ead638 pc=0x430da2
runtime.mapassign(0xdf27a0, 0xc01bd72150, 0xc01bd57670, 0xc01bd554d8)
        /usr/local/go/src/runtime/map.go:590 +0x5e3 fp=0xc013ead6f0 sp=0xc013ead668 pc=0x4128c3
reflect.mapassign(0xdf27a0, 0xc01bd72150, 0xc01bd57670, 0xc01bd57680)
        /usr/local/go/src/runtime/map.go:1331 +0x3f fp=0xc013ead720 sp=0xc013ead6f0 pc=0x41434f
reflect.Value.SetMapIndex(0xdf27a0, 0xc01ae5ad80, 0x195, 0xdbadc0, 0xc01bd57670, 0x198, 0xdbadc0, 0xc01bd57680, 0x198)
        /usr/local/go/src/reflect/value.go:1615 +0x234 fp=0xc013ead788 sp=0xc013ead720 pc=0x48e404
xxx/vendor/github.com/mediocregopher/radix/v3/resp/resp2.Any.unmarshalArray(0xd9d840, 0xc01ae5ad80, 0x0, 0xc014096cc0, 0x38, 0x0, 0x0)
        /data1/www/htdocs/xxx/vendor/github.com/mediocregopher/radix/v3/resp/resp2/resp.go:1039 +0x2b2 fp=0xc013ead960 sp=0xc013ead788 pc=0x813652
xxx/vendor/github.com/mediocregopher/radix/v3/resp/resp2.Any.UnmarshalRESP(0xd9d840, 0xc01ae5ad80, 0xc000350000, 0xc014096cc0, 0x0, 0x0)
        /data1/www/htdocs/xxx/vendor/github.com/mediocregopher/radix/v3/resp/resp2/resp.go:834 +0xa2b fp=0xc013eada58 sp=0xc013ead960 pc=0x811efb
xxx/vendor/github.com/mediocregopher/radix/v3.(*cmdAction).UnmarshalRESP(0xc00033c1c0, 0xc014096cc0, 0xe1cca0, 0xe92be0)
        /data1/www/htdocs/xxx/vendor/github.com/mediocregopher/radix/v3/action.go:267 +0x4c fp=0xc013eada98 sp=0xc013eada58 pc=0x8183dc
xxx/vendor/github.com/mediocregopher/radix/v3.(*connWrap).Decode(0xc013f90ae0, 0x10b2a00, 0xc00033c1c0, 0xc013eadb10, 0x40e355)
        /data1/www/htdocs/xxx/vendor/github.com/mediocregopher/radix/v3/radix.go:246 +0x42 fp=0xc013eadac8 sp=0xc013eada98 pc=0x81c912
xxx/vendor/github.com/mediocregopher/radix/v3.(*ioErrConn).Decode(0xc013f90b20, 0x10b2a00, 0xc00033c1c0, 0x10b2a00, 0xc00033c1c0)
        /data1/www/htdocs/xxx/vendor/github.com/mediocregopher/radix/v3/pool.go:51 +0x5c fp=0xc013eadb20 sp=0xc013eadac8 pc=0x819c8c
xxx/vendor/github.com/mediocregopher/radix/v3.pipeline.Run(0xc01bc76200, 0x4, 0x4, 0x10cf940, 0xc013f90b20, 0x4, 0xc00ca51000)
        /data1/www/htdocs/xxx/vendor/github.com/mediocregopher/radix/v3/action.go:445 +0x103 fp=0xc013eadb70 sp=0xc013eadb20 pc=0x818a13
xxx/vendor/github.com/mediocregopher/radix/v3.(*pipeline).Run(0xc01bbdaf40, 0x10cf940, 0xc013f90b20, 0x10c2940, 0xc0140fe870)
        <autogenerated>:1 +0x62 fp=0xc013eadbb8 sp=0xc013eadb70 pc=0x81fe32
xxx/vendor/github.com/mediocregopher/radix/v3.(*ioErrConn).Do(0xc013f90b20, 0x10c3c00, 0xc01bbdaf40, 0xc0140c6608, 0x4)
        /data1/www/htdocs/xxx/vendor/github.com/mediocregopher/radix/v3/pool.go:61 +0x47 fp=0xc013eadbf0 sp=0xc013eadbb8 pc=0x819e17
xxx/vendor/aaa/bbb/redis.(*redisPoolContext).Run(0xc01aa15580, 0x10cf940, 0xc013f90b20, 0x0, 0x149ec981752bda)
        /data1/www/htdocs/xxx/vendor/aaa/bbb/redis/redis.go:148 +0x108 fp=0xc013eadc48 sp=0xc013eadbf0 pc=0x821c98
xxx/vendor/github.com/mediocregopher/radix/v3.(*ioErrConn).Do(...)
        /data1/www/htdocs/xxx/vendor/github.com/mediocregopher/radix/v3/pool.go:61
xxx/vendor/github.com/mediocregopher/radix/v3.(*Pool).Do(0xc00026c100, 0x10c0c00, 0xc01aa15580, 0xc013eadd08, 0x40e0ed)
        /data1/www/htdocs/xxx/vendor/github.com/mediocregopher/radix/v3/pool.go:607 +0xf0 fp=0xc013eadcc0 sp=0xc013eadc48 pc=0x81be20
xxx/vendor/aaa/bbb/redis.(*RedisPool).Do(0xc012eaad20, 0x10cdf80, 0xc01aefa4d0, 0x10c3c00, 0xc01bbdaf40, 0x1, 0x1)
        /data1/www/htdocs/xxx/vendor/aaa/bbb/redis/redis.go:108 +0x192 fp=0xc013eadd48 sp=0xc013eadcc0 pc=0x821972
main.(*GateKeeper).writeContext(0xc013e6e9b0, 0x10cdf80, 0xc01aefa4d0, 0xc01bc4f521, 0x20, 0x0, 0x0, 0xc01bb95dd0)
        /data1/www/htdocs/xxx/gk/httphandel.go:689 +0x7f9 fp=0xc013eadfa0 sp=0xc013eadd48 pc=0xd0f749
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc013eadfa8 sp=0xc013eadfa0 pc=0x45d6f1
created by main.(*GateKeeper).HttpQeMatchHandel
        /data1/www/htdocs/xxx/gk/httphandel.go:783 +0xbda
```

**Comment by nussjustin** [comment]
Can you show us your code? Also there should be at least another stack trace (there need to be at least 2 goroutines writing to the map). This looks like you are using the same map in 2 concurrent `FlatCmd`s, which is not safe and will lead to this kind of error (or worse, data corruption).

**Comment by xuecai** [comment]
this will fatal error

go test -bench="BenchmarkPipeline" -race

```golang
func BenchmarkPipeline(b *testing.B) {
    redis1, _ := radix.NewPool("tcp", addr, 20)
    redis2, _ := radix.NewPool("tcp", addr, 20)
    b.RunParallel(func(pb *testing.PB) {
        for pb.Next() {
            nCmds := make([]radix.CmdAction, 0)
            nCmds1 := make([]radix.CmdAction, 0)
            var fqRet = make(map[string]string)
            rediskey := "aaaaa"
            rsSlice := make([]interface{}, 0)
            rsSlice = append(rsSlice, "key1", "value1")
            rsSlice = append(rsSlice, "key2", "value2")

            nCmds = append(nCmds, radix.FlatCmd(nil, "hmset", rediskey, rsSlice))
            nCmds = append(nCmds, radix.FlatCmd(nil, "expire", rediskey, "86400"))
            nCmds1 = append(nCmds, radix.FlatCmd(nil, "hmset", rediskey, rsSlice))
            nCmds1 = append(nCmds, radix.FlatCmd(nil, "expire", rediskey, "86400"))

            /*   
            if len(failIds) > 0 {
                nCmds = append(nCmds, glv2redis.FlatCmd(nil, "hdel", rediskey, failIds))
                nCmds1 = append(nCmds, glv2redis.FlatCmd(nil, "hdel", rediskey, failIds))
            }
            */
            nCmds = append(nCmds, radix.Cmd(nil, "hgetall", rediskey))
            nCmds1 = append(nCmds, radix.Cmd(&fqRet, "hgetall", rediskey))

            cmdsLen := len(nCmds)
            if cmdsLen > 0 {
                redis1.Do(Pipeline(nCmds1...))
                redis2.Do(Pipeline(nCmds...))
            }    
        }    
    })   
}

```


```shell
goos: linux
goarch: amd64
pkg: aaa/bbb/redis
BenchmarkPipeline-16            ==================
WARNING: DATA RACE
Read at 0x00c0004481c0 by goroutine 43:
  github.com/mediocregopher/radix/v3.(*cmdAction).UnmarshalRESP()
      /data1/www/htdocs/xuecai/gosrc/pkg/mod/github.com/mediocregopher/radix/v3@v3.3.0/action.go:289 +0x3e
  github.com/mediocregopher/radix/v3.(*connWrap).Decode()
      /data1/www/htdocs/xuecai/gosrc/pkg/mod/github.com/mediocregopher/radix/v3@v3.3.0/radix.go:229 +0x86
  github.com/mediocregopher/radix/v3.(*ioErrConn).Decode()
      /data1/www/htdocs/xuecai/gosrc/pkg/mod/github.com/mediocregopher/radix/v3@v3.3.0/pool.go:44 +0x68
  github.com/mediocregopher/radix/v3.pipeline.Run()
      /data1/www/htdocs/xuecai/gosrc/pkg/mod/github.com/mediocregopher/radix/v3@v3.3.0/action.go:465 +0x12f
  github.com/mediocregopher/radix/v3.(*pipeline).Run()
      <autogenerated>:1 +0x8a
  github.com/mediocregopher/radix/v3.(*ioErrConn).Do()
      /data1/www/htdocs/xuecai/gosrc/pkg/mod/github.com/mediocregopher/radix/v3@v3.3.0/pool.go:52 +0x54
  aaa/bbb/redis.(*redisPoolContext).Run()
      /data1/www/htdocs/xuecai/gosrc/src/aaa/bbb/redis/redis.go:148 +0x21c
  github.com/mediocregopher/radix/v3.(*Pool).Do()
      /data1/www/htdocs/xuecai/gosrc/pkg/mod/github.com/mediocregopher/radix/v3@v3.3.0/pool.go:52 +0x12d
  aaa/bbb/redis.(*RedisPool).Do()
      /data1/www/htdocs/xuecai/gosrc/src/aaa/bbb/redis/redis.go:108 +0x2ea
  aaa/bbb/redis.BenchmarkPipeline.func1()
      /data1/www/htdocs/xuecai/gosrc/src/aaa/bbb/redis/redis_test.go:208 +0xd23
  testing.(*B).RunParallel.func1()
      /usr/local/go/src/testing/benchmark.go:665 +0x160

Previous write at 0x00c0004481c0 by goroutine 126:
  github.com/mediocregopher/radix/v3.FlatCmd()
      /data1/www/htdocs/xuecai/gosrc/pkg/mod/github.com/mediocregopher/radix/v3@v3.3.0/action.go:208 +0x12f
  aaa/bbb/redis.BenchmarkPipeline.func1()
      /data1/www/htdocs/xuecai/gosrc/src/aaa/bbb/redis/redis_test.go:192 +0x5e2
  testing.(*B).RunParallel.func1()
      /usr/local/go/src/testing/benchmark.go:665 +0x160
```

**Comment by xuecai** [comment]
Thank you for reply me! It's bug in my code.
