### ISSUE TITLE
unable to create connection on Windows 32 bit machine's with GO MODULES

### ISSUE THREAD

**Issue by madhukant** [mediocregopher/radix#169]
I am unable to create the connection to the running redis when the go application is designed as GO MODULES on windows 32 bit computer. it works fine when being compiled and executed on 64 bit computer.

on 32 bit computer's golang module it's connect and immediately disconnect from redis.

**Comment by madhukant** [comment]
Adding snap of the PANIC:

C:\Users\######\Documents\Switch\redis_test
λ go build && .\redis_test.exe
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x4022ac]

goroutine 1 [running]:
runtime/internal/atomic.Xadd64(0x1244c1e4, 0x1, 0x0, 0x5c77b4, 0xe)
        c:/go/src/runtime/internal/atomic/asm_386.s:105 +0xc
github.com/mediocregopher/radix/v3.(*Pool).newConn(0x1244c160, 0x5c77b4, 0xe, 0x0, 0x0, 0x0)
        D:/#################/pkg/mod/github.com/mediocregopher/radix/v3@v3.4.1/pool.go:433 +0x111
github.com/mediocregopher/radix/v3.NewPool(0x5c586e, 0x3, 0x5c75d8, 0xe, 0xa, 0x0, 0x0, 0x0, 0x12436030, 0x0, ...)
        D:/#################/pkg/mod/github.com/mediocregopher/radix/v3@v3.4.1/pool.go:322 +0x347
main.main()
        C:/Users/######/Documents/Switch/redis_test/main.go:11 +0x77

**Comment by nussjustin** [comment]
Haven't tested this, but my guess is that the `totalsConn` field is not aligned correctly. Since we are using a 64-bit integer the struct field must be aligned to 64-bits on 32-bit architectures.

From the [sync/atomic](https://golang.org/sync/atomic/) documentation Bugs section:

> On ARM, x86-32, and 32-bit MIPS, it is the caller's responsibility to arrange for 64-bit alignment of 64-bit words accessed atomically. The first word in a variable or in an allocated struct, array, or slice can be relied upon to be 64-bit aligned.

@madhukant Can you try moving the `totalConns` field in the `Pool` struct before all other fields? It should look like this:

```go
type Pool struct {
	// totalConns is an atomic value and should only be accessed by the atomic
	// package.
	totalConns int64

	opts          poolOpts
	network, addr string
	size          int

	l sync.RWMutex
	// pool is read-protected by l, and should not be written to or read from
	// when closed is true (closed is also protected by l)
	pool   chan *ioErrConn
	closed bool

	pipeliner *pipeliner

	wg       sync.WaitGroup
	closeCh  chan bool
	initDone chan struct{} // used for tests

	// Any errors encountered internally will be written to this channel. If
	// nothing is reading the channel the errors will be dropped. The channel
	// will be closed when Close is called.
	ErrCh chan error
}
```

Having a 64-bit counter for the connections seems overkill anyway. If this is the problem we could just change it to 32-bit.

We should also check the alignment for the `lastClusterdown` field in the `Cluster` since this probably also isn't aligned correctly.

**Comment by nussjustin** [comment]
Checked the alignment using [structlayout](https://github.com/dominikh/go-tools/tree/master/cmd/structlayout).

For `Pool`:
```
Pool.opts.cf ..ConnFunc: 0-8 (size 8, align 8)
Pool.opts.pingInterval time.Duration: 8-16 (size 8, align 8)
Pool.opts.refillInterval time.Duration: 16-24 (size 8, align 8)
Pool.opts.overflowDrainInterval time.Duration: 24-32 (size 8, align 8)
Pool.opts.overflowSize int: 32-40 (size 8, align 8)
Pool.opts.onEmptyWait time.Duration: 40-48 (size 8, align 8)
Pool.opts.errOnEmpty error: 48-64 (size 16, align 8)
Pool.opts.pipelineConcurrency int: 64-72 (size 8, align 8)
Pool.opts.pipelineLimit int: 72-80 (size 8, align 8)
Pool.opts.pipelineWindow time.Duration: 80-88 (size 8, align 8)
Pool.opts.pt.ConnCreated func(github.com/mediocregopher/radix/v3/trace.PoolConnCreated): 88-96 (size 8, align 8)
Pool.opts.pt.ConnClosed func(github.com/mediocregopher/radix/v3/trace.PoolConnClosed): 96-104 (size 8, align 8)
Pool.opts.pt.DoCompleted func(github.com/mediocregopher/radix/v3/trace.PoolDoCompleted): 104-112 (size 8, align 8)
Pool.opts.pt.InitCompleted func(github.com/mediocregopher/radix/v3/trace.PoolInitCompleted): 112-120 (size 8, align 8)
Pool.network string: 120-136 (size 16, align 8)
Pool.addr string: 136-152 (size 16, align 8)
Pool.size int: 152-160 (size 8, align 8)
Pool.l.w.state int32: 160-164 (size 4, align 4)
Pool.l.w.sema uint32: 164-168 (size 4, align 4)
Pool.l.writerSem uint32: 168-172 (size 4, align 4)
Pool.l.readerSem uint32: 172-176 (size 4, align 4)
Pool.l.readerCount int32: 176-180 (size 4, align 4)
Pool.l.readerWait int32: 180-184 (size 4, align 4)
Pool.pool chan *..ioErrConn: 184-192 (size 8, align 8)
Pool.closed bool: 192-193 (size 1, align 1)
padding: 193-200 (size 7, align 0)
Pool.totalConns int64: 200-208 (size 8, align 8)
Pool.pipeliner *..pipeliner: 208-216 (size 8, align 8)
Pool.wg.noCopy sync.noCopy: 216-216 (size 0, align 1)
Pool.wg.state1 [3]uint32: 216-228 (size 12, align 4)
padding: 228-232 (size 4, align 0)
Pool.closeCh chan bool: 232-240 (size 8, align 8)
Pool.initDone chan struct{}: 240-248 (size 8, align 8)
Pool.ErrCh chan error: 248-256 (size 8, align 8)
```

For `Cluster`:
```
Cluster.co.pf ..ClientFunc: 0-8 (size 8, align 8)
Cluster.co.clusterDownWait time.Duration: 8-16 (size 8, align 8)
Cluster.co.syncEvery time.Duration: 16-24 (size 8, align 8)
Cluster.co.ct.StateChange func(github.com/mediocregopher/radix/v3/trace.ClusterStateChange): 24-32 (size 8, align 8)
Cluster.co.ct.TopoChanged func(github.com/mediocregopher/radix/v3/trace.ClusterTopoChanged): 32-40 (size 8, align 8)
Cluster.co.ct.Redirected func(github.com/mediocregopher/radix/v3/trace.ClusterRedirected): 40-48 (size 8, align 8)
Cluster.syncDedupe *..dedupe: 48-56 (size 8, align 8)
Cluster.lastClusterdown int64: 56-64 (size 8, align 8)
Cluster.l.w.state int32: 64-68 (size 4, align 4)
Cluster.l.w.sema uint32: 68-72 (size 4, align 4)
Cluster.l.writerSem uint32: 72-76 (size 4, align 4)
Cluster.l.readerSem uint32: 76-80 (size 4, align 4)
Cluster.l.readerCount int32: 80-84 (size 4, align 4)
Cluster.l.readerWait int32: 84-88 (size 4, align 4)
Cluster.pools map[string]..Client: 88-96 (size 8, align 8)
Cluster.primTopo ..ClusterTopo: 96-120 (size 24, align 8)
Cluster.topo ..ClusterTopo: 120-144 (size 24, align 8)
Cluster.closeCh chan struct{}: 144-152 (size 8, align 8)
Cluster.closeWG.noCopy sync.noCopy: 152-152 (size 0, align 1)
Cluster.closeWG.state1 [3]uint32: 152-164 (size 12, align 4)
Cluster.closeOnce.done uint32: 164-168 (size 4, align 4)
Cluster.closeOnce.m.state int32: 168-172 (size 4, align 4)
Cluster.closeOnce.m.sema uint32: 172-176 (size 4, align 4)
Cluster.ErrCh chan error: 176-184 (size 8, align 8)
```

Both fields are not aligned correctly.

**Comment by nussjustin** [comment]
I can't currently push a PR, but may later once I'm home. In the mean time here is the fix:

```diff
diff --git a/cluster.go b/cluster.go
index faaf4d1..316c51e 100644
--- a/cluster.go
+++ b/cluster.go
@@ -110,13 +110,16 @@ func ClusterWithTrace(ct trace.ClusterTrace) ClusterOpt {
 // with it, including a set of pools to each of its instances. All methods on
 // Cluster are thread-safe
 type Cluster struct {
+	// Atomic fields must be at the beginning of the struct since they must be
+	// correctly aligned or else access may cause panics on 32-bit architectures
+	// See https://golang.org/pkg/sync/atomic/#pkg-note-BUG
+	lastClusterdown int64 // unix timestamp in milliseconds, atomic
+
 	co clusterOpts
 
 	// used to deduplicate calls to sync
 	syncDedupe *dedupe
 
-	lastClusterdown int64 // unix timestamp in milliseconds, atomic
-
 	l              sync.RWMutex
 	pools          map[string]Client
 	primTopo, topo ClusterTopo
diff --git a/pool.go b/pool.go
index 339536a..9d35c1a 100644
--- a/pool.go
+++ b/pool.go
@@ -236,6 +236,11 @@ func PoolWithTrace(pt trace.PoolTrace) PoolOpt {
 // performance during low-concurrency usage. It can be disabled using
 // PoolPipelineWindow(0, 0).
 type Pool struct {
+	// Atomic fields must be at the beginning of the struct since they must be
+	// correctly aligned or else access may cause panics on 32-bit architectures
+	// See https://golang.org/pkg/sync/atomic/#pkg-note-BUG
+	totalConns int64 // atomic, must only be access using functions from sync/atomic
+
 	opts          poolOpts
 	network, addr string
 	size          int
@@ -246,9 +251,6 @@ type Pool struct {
 	pool   chan *ioErrConn
 	closed bool
 
-	// totalConns is an atomic value and should only be accessed by the atomic
-	// package.
-	totalConns int64
 
 	pipeliner *pipeliner
```

@mediocregopher If you're faster than me you are to commit it yourself. Commit message should probably also mention the tool used for checking. E.g.


```diff
    Fix alignment for atomic values in structs
    
    Checked via github.com/dominikh/go-tools/cmd/structlayout
```

**Comment by madhukant** [comment]
Changing the struct as suggested worked file with 32 bit architecture. I have tested pool as well as cluster code.
