### ISSUE TITLE
EncodeDecode panic (v4)

### ISSUE THREAD

**Issue by kollektiv** [mediocregopher/radix#253]
Hello, our application ran into a panic with the v4.0.0-beta.1 client. The application is making lots of GET commands

Stack trace
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7b7366]
goroutine 101049 [running]:
github.com/mediocregopher/radix/v4.(*poolConn).EncodeDecode(0x0, 0xc49d40, 0xc000116000, 0xabcd80, 0xc0014325b0, 0xabcd80, 0xc0014325b0, 0x17c4f534b6, 0xf80ec0)
/root/app/vendor/github.com/mediocregopher/radix/v4/pool.go:34 +0x26
github.com/mediocregopher/radix/v4.(*cmdAction).Perform(0xc0014325b0, 0xc49d40, 0xc000116000, 0xc4a000, 0x0, 0xf852a0, 0xf852b0)
/root/app/vendor/github.com/mediocregopher/radix/v4/action.go:270 +0x65
github.com/mediocregopher/radix/v4.(*poolConn).Do(...)
/root/app/vendor/github.com/mediocregopher/radix/v4/pool.go:45
github.com/mediocregopher/radix/v4.(*pool).useSharedConn.func1(0xc00001f008, 0xc00170aa00)
/root/app/vendor/github.com/mediocregopher/radix/v4/pool.go:407 +0x102
github.com/mediocregopher/radix/v4/internal/proc.(*Proc).WithRLock(0xc00001efc0, 0xc0007139d8, 0x0, 0x0)
/root/app/vendor/github.com/mediocregopher/radix/v4/internal/proc/proc.go:104 +0xae
github.com/mediocregopher/radix/v4.(*pool).useSharedConn(0xc000308ea0, 0xc49d40, 0xc000116000, 0xc438c0, 0xc0014325b0, 0x40df58, 0x60)
/root/app/vendor/github.com/mediocregopher/radix/v4/pool.go:400 +0xc5
github.com/mediocregopher/radix/v4.(*pool).Do(0xc000308ea0, 0xc49d40, 0xc000116000, 0xc438c0, 0xc0014325b0, 0x7b9173, 0xc0000dc120)
/root/app/vendor/github.com/mediocregopher/radix/v4/pool.go:429 +0x18f
github.com/mediocregopher/radix/v4.(*Cluster).doInner(0xc000308b40, 0xc49d40, 0xc000116000, 0xc438c0, 0xc0014325b0, 0xc000d48220, 0x13, 0xc0010ed708, 0x6, 0xc47c40, ...)
/root/app/vendor/github.com/mediocregopher/radix/v4/cluster.go:709 +0xea
github.com/mediocregopher/radix/v4.(*Cluster).Do(0xc000308b40, 0xc49d40, 0xc000116000, 0xc438c0, 0xc0014325b0, 0x1, 0x0)
/root/app/vendor/github.com/mediocregopher/radix/v4/cluster.go:544 +0x17d
```

**Comment by kollektiv** [comment]
Hello, I cannot reproduce the panic with https://github.com/mediocregopher/radix/commit/9f32b1f5a6913c132af40f9a7638626c2cf17411
