### ISSUE TITLE
Panic appending action to pipeline (v4)

### ISSUE THREAD

**Issue by kollektiv** [mediocregopher/radix#256]
Hello, captured a panic when trying to append an action to a pipeline

The code is doing something like

```go
var ret string
maybe := radix.Maybe{
	Rcv: &ret,
}

action := radix.FlatCmd(&maybe, "SET", key, value, "NX")
pipeline := radix.NewPipeline()
pipeline.Append(action)
```

```
panic: can't pipeline Action of type *radix.cmdAction: ["SET" "389359" "KLQGPwJxfXUTVSrZTiHAyDcNcsCtgOtEWEilePFRZNZDALpAneqmH" "EX" "600" "NX"]
goroutine 396748 [running]:
github.com/mediocregopher/radix/v4.(*pipeline).append(0xc00647acc0, 0xc44ac0, 0xc0044ac620)
/root/app/vendor/github.com/mediocregopher/radix/v4/action.go:503 +0x32a
github.com/mediocregopher/radix/v4.(*Pipeline).Append(...)
/root/app/vendor/github.com/mediocregopher/radix/v4/action.go:645
```

This may be related to https://github.com/mediocregopher/radix/issues/254

**Comment by mediocregopher** [comment]
@kollektiv is this still an issue, or was it fixed by the fixes for your other issues?
