### ISSUE TITLE
V4: TestSentinel is broken

### ISSUE THREAD

**Issue by mediocregopher** [mediocregopher/radix#282]
When running TestSentinel with `-race` on it sometimes hangs. The stacktrace when it's hanging is as follows:

```
goroutine 0 [idle]:
runtime.epollwait(0x3, 0x7fff3220ec90, 0x3e700000080, 0x0, 0x3e7, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/lib/go/src/runtime/sys_linux_amd64.s:725 +0x20
runtime.netpoll(0x3b9a06d0, 0x0)
        /usr/lib/go/src/runtime/netpoll_epoll.go:126 +0x92
runtime.findrunnable(0xc000031800, 0x0)
        /usr/lib/go/src/runtime/proc.go:2923 +0x3ee
runtime.schedule()
        /usr/lib/go/src/runtime/proc.go:3169 +0x2d7
runtime.park_m(0xc0004c7e00)
        /usr/lib/go/src/runtime/proc.go:3318 +0x9d
runtime.mcall(0x0)
        /usr/lib/go/src/runtime/asm_amd64.s:327 +0x5b

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000419980, 0x96a671, 0xc, 0x983f30, 0x1)
        /usr/lib/go/src/testing/testing.go:1239 +0x610
testing.runTests.func1(0xc000419980)
        /usr/lib/go/src/testing/testing.go:1511 +0xa7
testing.tRunner(0xc000419980, 0xc0000b3ce0)
        /usr/lib/go/src/testing/testing.go:1193 +0x203
testing.runTests(0xc0000bc9a8, 0xc1b100, 0x3c, 0x3c, 0xc0274fe943f16a8e, 0x8bc5ef6725, 0xc204c0, 0xc0000aa1a8)
        /usr/lib/go/src/testing/testing.go:1509 +0x613
testing.(*M).Run(0xc00044a100, 0x0)
        /usr/lib/go/src/testing/testing.go:1417 +0x3b4
main.main()
        _testmain.go:183 +0x237

goroutine 1398 [select]:
github.com/mediocregopher/radix/v4.(*pubSubConn).pubSpin(0xc000148aa0, 0xa26330, 0xc0000e92c0)
        /home/mediocregopher/src/radix/pubsub.go:313 +0x265
github.com/mediocregopher/radix/v4/internal/proc.(*Proc).Run.func1(0xc0001a6c10, 0xc00011c9c0)
        /home/mediocregopher/src/radix/internal/proc/proc.go:45 +0x5a
created by github.com/mediocregopher/radix/v4/internal/proc.(*Proc).Run
        /home/mediocregopher/src/radix/internal/proc/proc.go:44 +0x74

goroutine 1386 [select]:
github.com/mediocregopher/radix/v4.(*connWriter).run(0xc000115ef0)
        /home/mediocregopher/src/radix/conn_writer.go:134 +0x211
github.com/mediocregopher/radix/v4.(*conn).writer(0xc0000fed90, 0xa26330, 0xc0000e9080, 0x0)
        /home/mediocregopher/src/radix/conn_writer.go:51 +0x148
github.com/mediocregopher/radix/v4.Dialer.Dial.func1(0xa26330, 0xc0000e9080)
        /home/mediocregopher/src/radix/conn.go:474 +0x5f
github.com/mediocregopher/radix/v4/internal/proc.(*Proc).Run.func1(0xc0005a0c80, 0xc000283bc0)
        /home/mediocregopher/src/radix/internal/proc/proc.go:45 +0x5a
created by github.com/mediocregopher/radix/v4/internal/proc.(*Proc).Run
        /home/mediocregopher/src/radix/internal/proc/proc.go:44 +0x74

goroutine 1375 [semacquire]:
sync.runtime_Semacquire(0xc000282d58)
        /usr/lib/go/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc000282d50)
        /usr/lib/go/src/sync/waitgroup.go:130 +0xe5
github.com/mediocregopher/radix/v4/internal/proc.(*Proc).PrefixedClose.func1()
        /home/mediocregopher/src/radix/internal/proc/proc.go:70 +0x125
sync.(*Once).doSlow(0xc000282d40, 0xc0005cd880)
        /usr/lib/go/src/sync/once.go:68 +0x10a
sync.(*Once).Do(0xc000282d40, 0xc0005cd880)
        /usr/lib/go/src/sync/once.go:59 +0x69
github.com/mediocregopher/radix/v4/internal/proc.(*Proc).PrefixedClose(0xc000282d20, 0x984060, 0xc0005cd930, 0x63e079, 0xc000282d5c)
        /home/mediocregopher/src/radix/internal/proc/proc.go:62 +0xba
github.com/mediocregopher/radix/v4/internal/proc.(*Proc).Close(0xc000282d20, 0xc0005cd930, 0xc0005cdf08, 0x0)
        /home/mediocregopher/src/radix/internal/proc/proc.go:55 +0x4f
github.com/mediocregopher/radix/v4.(*Sentinel).Close(0xc0000b41a0, 0xc0005cdb48, 0x0)
        /home/mediocregopher/src/radix/sentinel.go:265 +0x73
github.com/mediocregopher/radix/v4.TestSentinel(0xc000419b00)
        /home/mediocregopher/src/radix/sentinel_test.go:231 +0xa4a
testing.tRunner(0xc000419b00, 0x983f30)
        /usr/lib/go/src/testing/testing.go:1193 +0x203
created by testing.(*T).Run
        /usr/lib/go/src/testing/testing.go:1238 +0x5d8

goroutine 1389 [select]:
github.com/mediocregopher/radix/v4.(*pool).atIntervalDo.func1(0xa26330, 0xc0000e9040)
        /home/mediocregopher/src/radix/pool.go:294 +0x1a5
github.com/mediocregopher/radix/v4/internal/proc.(*Proc).Run.func1(0xc00000f308, 0xc000283b60)
        /home/mediocregopher/src/radix/internal/proc/proc.go:45 +0x5a
created by github.com/mediocregopher/radix/v4/internal/proc.(*Proc).Run
        /home/mediocregopher/src/radix/internal/proc/proc.go:44 +0x74

goroutine 1397 [select]:
github.com/mediocregopher/radix/v4.(*pubSubStub).spin(0xc000148a50, 0xa26330, 0xc0000e9200)
        /home/mediocregopher/src/radix/pubsub_stub.go:166 +0x165
github.com/mediocregopher/radix/v4/internal/proc.(*Proc).Run.func1(0xc0001a6bd0, 0xc00011c840)
        /home/mediocregopher/src/radix/internal/proc/proc.go:45 +0x5a
created by github.com/mediocregopher/radix/v4/internal/proc.(*Proc).Run
        /home/mediocregopher/src/radix/internal/proc/proc.go:44 +0x74

goroutine 1395 [select]:
github.com/mediocregopher/radix/v4.(*pool).atIntervalDo.func1(0xa26330, 0xc0000e9100)
        /home/mediocregopher/src/radix/pool.go:294 +0x1a5
github.com/mediocregopher/radix/v4/internal/proc.(*Proc).Run.func1(0xc00000f398, 0xc000283f80)
        /home/mediocregopher/src/radix/internal/proc/proc.go:45 +0x5a
created by github.com/mediocregopher/radix/v4/internal/proc.(*Proc).Run
        /home/mediocregopher/src/radix/internal/proc/proc.go:44 +0x74

goroutine 1396 [select]:
github.com/mediocregopher/radix/v4.(*stub).responder(0xc0000e9280, 0xa26330, 0xc0000e9240)
        /home/mediocregopher/src/radix/stub.go:81 +0xe6f
github.com/mediocregopher/radix/v4/internal/proc.(*Proc).Run.func1(0xc0001a6bc0, 0xc00011c8a0)
        /home/mediocregopher/src/radix/internal/proc/proc.go:45 +0x5a
created by github.com/mediocregopher/radix/v4/internal/proc.(*Proc).Run
        /home/mediocregopher/src/radix/internal/proc/proc.go:44 +0x74

goroutine 1399 [select]:
github.com/mediocregopher/radix/v4.(*stub).EncodeDecode(0xc0000e9280, 0xa263a0, 0xc00011ccc0, 0x0, 0x0, 0x90b8c0, 0xc00008e0f0, 0xc0000e92c0, 0x0)
        /home/mediocregopher/src/radix/stub.go:170 +0x4af
github.com/mediocregopher/radix/v4.(*pubSubConn).spin(0xc000148aa0, 0xa26330, 0xc0000e92c0)
        /home/mediocregopher/src/radix/pubsub.go:341 +0x179
github.com/mediocregopher/radix/v4/internal/proc.(*Proc).Run.func1(0xc0001a6c20, 0xc00011c9c0)
        /home/mediocregopher/src/radix/internal/proc/proc.go:45 +0x5a
created by github.com/mediocregopher/radix/v4/internal/proc.(*Proc).Run
        /home/mediocregopher/src/radix/internal/proc/proc.go:44 +0x74

goroutine 1303 [semacquire]:
sync.runtime_SemacquireMutex(0xc000148734, 0x900000000, 0x1)
        /usr/lib/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc000148730)
        /usr/lib/go/src/sync/mutex.go:138 +0x1d4
sync.(*Mutex).Lock(0xc000148730)
        /usr/lib/go/src/sync/mutex.go:81 +0x85
github.com/mediocregopher/radix/v4.(*sentinelStub).newConn.func1(0xa263a0, 0xc000300900, 0xc000302660, 0x3, 0x3, 0x0, 0x0)
        /home/mediocregopher/src/radix/sentinel_test.go:77 +0x8a
github.com/mediocregopher/radix/v4.(*pubSubStub).innerFn.func1(0xc0002a602c, 0x0)
        /home/mediocregopher/src/radix/pubsub_stub.go:148 +0x78e
github.com/mediocregopher/radix/v4/internal/proc.(*Proc).WithLock(0xc0002a6000, 0xc0000b3be8, 0x0, 0x0)
        /home/mediocregopher/src/radix/internal/proc/proc.go:116 +0xf5
github.com/mediocregopher/radix/v4.(*pubSubStub).innerFn(0xc0004c0000, 0xa263a0, 0xc000300900, 0xc000302660, 0x3, 0x3, 0xc0000b3e88, 0x938901)
        /home/mediocregopher/src/radix/pubsub_stub.go:77 +0xf7
github.com/mediocregopher/radix/v4.(*stub).responder(0xc0000e8a40, 0xa26330, 0xc0000e83c0)
        /home/mediocregopher/src/radix/stub.go:86 +0x28a
github.com/mediocregopher/radix/v4/internal/proc.(*Proc).Run.func1(0xc0005ec040, 0xc0002a6060)
        /home/mediocregopher/src/radix/internal/proc/proc.go:45 +0x5a
created by github.com/mediocregopher/radix/v4/internal/proc.(*Proc).Run
        /home/mediocregopher/src/radix/internal/proc/proc.go:44 +0x74

goroutine 1392 [select]:
github.com/mediocregopher/radix/v4.(*connWriter).run(0xc000130ef0)
        /home/mediocregopher/src/radix/conn_writer.go:134 +0x211
github.com/mediocregopher/radix/v4.(*conn).writer(0xc0000fee00, 0xa26330, 0xc0000e9140, 0x0)
        /home/mediocregopher/src/radix/conn_writer.go:51 +0x148
github.com/mediocregopher/radix/v4.Dialer.Dial.func1(0xa26330, 0xc0000e9140)
        /home/mediocregopher/src/radix/conn.go:474 +0x5f
github.com/mediocregopher/radix/v4/internal/proc.(*Proc).Run.func1(0xc0005a0e80, 0xc00011c120)
        /home/mediocregopher/src/radix/internal/proc/proc.go:45 +0x5a
created by github.com/mediocregopher/radix/v4/internal/proc.(*Proc).Run
        /home/mediocregopher/src/radix/internal/proc/proc.go:44 +0x74

goroutine 1400 [select]:
github.com/mediocregopher/radix/v4.(*persistentPubSub).spin(0xc00014c5b0, 0xa26330, 0xc0000e91c0)
        /home/mediocregopher/src/radix/pubsub_persistent.go:226 +0x1da
github.com/mediocregopher/radix/v4/internal/proc.(*Proc).Run.func1(0xc0001a6c30, 0xc00011c7e0)
        /home/mediocregopher/src/radix/internal/proc/proc.go:45 +0x5a
created by github.com/mediocregopher/radix/v4/internal/proc.(*Proc).Run
        /home/mediocregopher/src/radix/internal/proc/proc.go:44 +0x74

goroutine 1360 [semacquire]:
sync.runtime_SemacquireMutex(0xc0002a6040, 0x900000000, 0x1)
        /usr/lib/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc0002a603c)
        /usr/lib/go/src/sync/mutex.go:138 +0x1d4
sync.(*Mutex).Lock(0xc0002a603c)
        /usr/lib/go/src/sync/mutex.go:81 +0x85
sync.(*RWMutex).Lock(0xc0002a603c)
        /usr/lib/go/src/sync/rwmutex.go:111 +0x4a
github.com/mediocregopher/radix/v4/internal/proc.(*Proc).PrefixedClose.func1()
        /home/mediocregopher/src/radix/internal/proc/proc.go:66 +0xea
sync.(*Once).doSlow(0xc0002a6020, 0xc0000b1be8)
        /usr/lib/go/src/sync/once.go:68 +0x10a
sync.(*Once).Do(0xc0002a6020, 0xc0000b1be8)
        /usr/lib/go/src/sync/once.go:59 +0x69
github.com/mediocregopher/radix/v4/internal/proc.(*Proc).PrefixedClose(0xc0002a6000, 0x984060, 0xc0000b1c98, 0x7ff24c150008, 0xc000148730)
        /home/mediocregopher/src/radix/internal/proc/proc.go:62 +0xba
github.com/mediocregopher/radix/v4/internal/proc.(*Proc).Close(0xc0002a6000, 0xc0000b1c98, 0x1, 0x2ac83f7255d4d0cb)
        /home/mediocregopher/src/radix/internal/proc/proc.go:55 +0x4f
github.com/mediocregopher/radix/v4.(*pubSubStub).Close(0xc0004c0000, 0xc000142330, 0xc000118000)
        /home/mediocregopher/src/radix/pubsub_stub.go:159 +0x73
github.com/mediocregopher/radix/v4.(*sentinelStubConn).Close(0xc0000d6040, 0x0, 0x0)
        /home/mediocregopher/src/radix/sentinel_test.go:57 +0x162
github.com/mediocregopher/radix/v4.(*Sentinel).innerSpin(0xc0000b41a0, 0xa26330, 0xc0000e8e80, 0xa208a0, 0xc0000281a0)
        /home/mediocregopher/src/radix/sentinel.go:465 +0x3b6
github.com/mediocregopher/radix/v4.(*Sentinel).spin(0xc0000b41a0, 0xa26330, 0xc0000e8e80)
        /home/mediocregopher/src/radix/sentinel.go:410 +0xd3
github.com/mediocregopher/radix/v4/internal/proc.(*Proc).Run.func1(0xc00011a130, 0xc000282d20)
        /home/mediocregopher/src/radix/internal/proc/proc.go:45 +0x5a
created by github.com/mediocregopher/radix/v4/internal/proc.(*Proc).Run
        /home/mediocregopher/src/radix/internal/proc/proc.go:44 +0x74

goroutine 1387 [select]:
github.com/mediocregopher/radix/v4.(*pool).runReconnect.func1(0xa26330, 0xc0000e9040)
        /home/mediocregopher/src/radix/pool.go:316 +0x249
github.com/mediocregopher/radix/v4/internal/proc.(*Proc).Run.func1(0xc0000d6ae0, 0xc000283b60)
        /home/mediocregopher/src/radix/internal/proc/proc.go:45 +0x5a
created by github.com/mediocregopher/radix/v4/internal/proc.(*Proc).Run
        /home/mediocregopher/src/radix/internal/proc/proc.go:44 +0x74

goroutine 1391 [select]:
github.com/mediocregopher/radix/v4.(*conn).reader(0xc0000fee00, 0xa26330, 0xc0000e9140)
        /home/mediocregopher/src/radix/conn.go:122 +0x167
github.com/mediocregopher/radix/v4/internal/proc.(*Proc).Run.func1(0xc0001a6b30, 0xc00011c120)
        /home/mediocregopher/src/radix/internal/proc/proc.go:45 +0x5a
created by github.com/mediocregopher/radix/v4/internal/proc.(*Proc).Run
        /home/mediocregopher/src/radix/internal/proc/proc.go:44 +0x74

goroutine 1385 [select]:
github.com/mediocregopher/radix/v4.(*conn).reader(0xc0000fed90, 0xa26330, 0xc0000e9080)
        /home/mediocregopher/src/radix/conn.go:122 +0x167
github.com/mediocregopher/radix/v4/internal/proc.(*Proc).Run.func1(0xc0001a6a40, 0xc000283bc0)
        /home/mediocregopher/src/radix/internal/proc/proc.go:45 +0x5a
created by github.com/mediocregopher/radix/v4/internal/proc.(*Proc).Run
        /home/mediocregopher/src/radix/internal/proc/proc.go:44 +0x74

goroutine 1393 [select]:
github.com/mediocregopher/radix/v4.(*pool).runReconnect.func1(0xa26330, 0xc0000e9100)
        /home/mediocregopher/src/radix/pool.go:316 +0x249
github.com/mediocregopher/radix/v4/internal/proc.(*Proc).Run.func1(0xc0000d6b60, 0xc000283f80)
        /home/mediocregopher/src/radix/internal/proc/proc.go:45 +0x5a
created by github.com/mediocregopher/radix/v4/internal/proc.(*Proc).Run
        /home/mediocregopher/src/radix/internal/proc/proc.go:44 +0x74
```

I _think_ this might be related to #281, as I think the test is getting into a deadlock when Close is called somewhere.

**Comment by mediocregopher** [comment]
This is fixed as of the new pubsub code, which also fixed the Stub type.
