### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by cbroglie** [mediocregopher/radix#64]
I encountered this after closing a pool as part of cleanup for an integration test. I think you need to acquire the mutex before sending the PING, in case of a race between that timer and the channel being closed?

```go
goroutine 1737 [running]:
github.com/mediocregopher/radix/v3.(*pipeliner).Do(0xc0000d6720, 0xd16900, 0xc00042e3f0, 0xbc2c01, 0xc02b20)
	/build/src/.../vendor/github.com/mediocregopher/radix/v3/pipeliner.go:102 +0x161
github.com/mediocregopher/radix/v3.(*Pool).Do(0xc000246000, 0xd16900, 0xc00042e3f0, 0x0, 0x0)
	/build/src/.../vendor/github.com/mediocregopher/radix/v3/pool.go:497 +0x1b8
github.com/mediocregopher/radix/v3.NewPool.func2()
	/build/src/.../vendor/github.com/mediocregopher/radix/v3/pool.go:309 +0xb7
github.com/mediocregopher/radix/v3.(*Pool).atIntervalDo.func1(0xc000246000, 0x2f362b6, 0xc0002ddb60)
	/build/src/.../vendor/github.com/mediocregopher/radix/v3/pool.go:354 +0xc5
created by github.com/mediocregopher/radix/v3.(*Pool).atIntervalDo
	/build/src/.../vendor/github.com/mediocregopher/radix/v3/pool.go:347 +0x85
```

**Comment by mediocregopher** [comment]
Awesome, thanks guys!
